INSERT INTO usuario(nombre,contra)VALUES('admin','admin')
INSERT INTO usuario(nombre,contra)VALUES('mo','mo')
INSERT INTO usuario(nombre,contra)VALUES('paco','paquito')

INSERT INTO nota (id,nota)VALUES(0,0)
INSERT INTO nota (id,nota)VALUES(1,1)
INSERT INTO nota (id,nota)VALUES(2,2)
INSERT INTO nota (id,nota)VALUES(3,3)
INSERT INTO nota (id,nota)VALUES(4,4)
INSERT INTO nota (id,nota)VALUES(5,5)
INSERT INTO nota (id,nota)VALUES(6,6)
INSERT INTO nota (id,nota)VALUES(7,7)
INSERT INTO nota (id,nota)VALUES(8,8)
INSERT INTO nota (id,nota)VALUES(9,9)
INSERT INTO nota (id,nota)VALUES(10,10)

INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (1,'Martial peak','Momo','artes marciales',true,10)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (2,'Zipang','Kawaguchi Kaiji','historico',false,8)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (3,'One Piece','Eichiro Oda','aventura',true,9)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (4,'Hajime no Ippo','MORIKAWA George','deportes',true,8)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (5,'Beastars','Itagaki Paru','psicologico',true,7)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (6,'Baki','Keisuke Itagaki','artes marciales',false,7)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (7,'Overlord','Kugane Maruyama','isekai',true,8)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (8,'Monster','Naoki Urasawaga','Misterio',false,9)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (9,'Billy bat','Naoki Urasawaga','Misterio',false,10)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (10,'20th Century boys','Naoki Urasawaga','Misterio',false,9)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (11,'Berserk','Kentaro Miura','Fantasia',true,10)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (12,'Rent a girlfriend','Reiji Miyajima','Romance',true,0)
INSERT INTO manga(id,titulo,autor,genero,emision,nota_id) VALUES (13,'Solo leveling','Chu-Gong','Accion',false,7)



INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Zipang','Kawaguchi Kaiji','historico',false,2,6)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('One Piece','Eichiro Oda','aventura',true,3,8)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Hajime no Ippo','MORIKAWA George','deportes',true,4,7)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Beastars','Itagaki Paru','psicologico',true,5,6)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Baki','Keisuke Itagaki','artes marciales',false,6,6)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Overlord','Kugane Maruyama','isekai',true,7,7)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Monster','Naoki Urasawaga','Misterio',false,8,9)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('SSSS.Gridman','Keiichi Hasegawa','Mechas',false,null,9)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Tengen Toppa Gurren Lagan','Hiroyuki Imaishi','Mechas',false,null,8)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Samurai Champloo','Shinichirō Watanabe','Historico',false,null,9)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Rent a girlfriend','Reiji Miyajima','Romance',true,12,1)
INSERT INTO anime(titulo,autor,genero,emision,manga_id,nota_id) VALUES ('Solo leveling','Chu-Gong','Acion',true,13,5)



